import {
  coldarkColdTheme,
  coldarkDarkTheme,
  draculaTheme,
  duotoneDarkTheme,
  duotoneSeaTheme,
  lightTheme,
  materialLightTheme,
  materialOceanTheme,
  materialPalenightTheme,
  materialVolcanoTheme,
  nightOwlTheme,
  oneDarkTheme,
  synthwave84Theme,
  vsCodeDarkTheme,
} from '@codeimage/theme';

export const SUPPORTED_THEMES = [
  vsCodeDarkTheme,
  nightOwlTheme,
  draculaTheme,
  materialOceanTheme,
  synthwave84Theme,
  materialVolcanoTheme,
  oneDarkTheme,
  lightTheme,
  materialPalenightTheme,
  // TODO: to refactor -> ugly themes
  // arcDarkTheme,
  // holiTheme,
  duotoneSeaTheme,
  duotoneDarkTheme,
  coldarkColdTheme,
  coldarkDarkTheme,
  materialLightTheme,
] as const;
