import {
  arcDarkTheme,
  coldarkColdTheme,
  coldarkDarkTheme,
  draculaTheme,
  duotoneDarkTheme,
  duotoneSeaTheme,
  holiTheme,
  lightTheme,
  materialOceanTheme,
  materialVolcanoTheme,
  nightOwlTheme,
  oneDarkTheme,
  synthwave84Theme,
  vsCodeDarkTheme,
} from '@codeimage/theme';

export const SUPPORTED_THEMES = [
  oneDarkTheme,
  lightTheme,
  materialOceanTheme,
  draculaTheme,
  synthwave84Theme,
  materialVolcanoTheme,
  arcDarkTheme,
  vsCodeDarkTheme,
  holiTheme,
  duotoneSeaTheme,
  duotoneDarkTheme,
  coldarkColdTheme,
  coldarkDarkTheme,
  nightOwlTheme,
] as const;
