import {createTheme} from '@vanilla-extract/css';
import {colors} from './theme.css';
import {themeVars} from './global.css';

export const darkThemeCss = createTheme(colors, {
  primary: themeVars.backgroundColor.blue['400'],
  panelBackground: '#111111',
  panelTextColor: themeVars.backgroundColor.white,
  background: '#181818',
  baseText: themeVars.textColor.gray['800'],
  descriptionTextColor: '#999999',
  secondary: themeVars.backgroundColor.gray['200'],
  divider: '#252525',
  inputBackgroundColor: '#2B2B2B',
  inputBorderColor: '#252525',
  inputTextColor: '#EEEEEE',
  inputLabelTextColor: '#FFFFFF',
  inputAccentColor: '#555555',
  buttonBackgroundColor: '#333333',
  buttonBackgroundActive: '#232323',
  buttonBackgroundHover: '#282828',
  buttonTextColor: themeVars.backgroundColor.white,
  buttonBackgroundPrimaryColor: themeVars.backgroundColor.blue['500'],
  buttonBackgroundPrimaryActive: themeVars.backgroundColor.blue['700'],
  buttonBackgroundPrimaryHover: themeVars.backgroundColor.blue['600'],
  buttonTextPrimaryColor: themeVars.backgroundColor.white,
  menuBackground: '#2b2b2b',
  resizeLineBackgroundColor: 'hsla(0,0%,100%,.25)',
  resizeLineBadgeBackgroundColor: '#161515',
  listBoxPanelBackground: '#2B2B2B',
  listBoxActiveBackgroundColor: themeVars.backgroundColor.blue['500'],
  listBoxHoverBackgroundColor: `#232323`,
  listBoxTextColor: themeVars.backgroundColor.white,
  listBoxActiveTextColor: themeVars.backgroundColor.white,
  scrollBarBackgroundColor: '#555555',
  scrollBarHoverBackgroundColor: '#333333',
  bottomBarBackgroundColor: '#2B2B2B',
  bottomBarTextColor: '#EEEEEE',
  emptySquareBackgroundColor: '#252525',
  snackbarBackgroundColor: '#EEEEEE',
  snackbarTextColor: themeVars.textColor.gray['800'],
  frameDragControlBackgroundColor: `#EEEEEE`,
  dialogOverlayBackgroundColor: 'rgba(0,0,0,.7)',
  dialogPanelBackgroundColor: '#1d1d1d',
  dialogPanelShadow:
    '0px 10px 30px 0px rgba(0,0,0,.15),inset 0 0 0 1px #222222',
  dialogTitleTextColor: '#EEEEEE',
  dialogTitleBorderColor: '#2B2B2B',
  dialogPanelTextColor: '#EEEEEE',
});
