import {createThemeContract} from '@vanilla-extract/css';

export const colors = createThemeContract({
  primary: null,
  secondary: null,
  background: null,
  panelBackground: null,
  panelTextColor: null,
  baseText: null,
  descriptionTextColor: null,
  divider: null,
  inputBackgroundColor: null,
  inputBorderColor: null,
  inputTextColor: null,
  inputAccentColor: null,
  buttonBackgroundPrimaryColor: null,
  buttonBackgroundPrimaryActive: null,
  buttonBackgroundPrimaryHover: null,
  buttonTextPrimaryColor: null,
  buttonBackgroundColor: null,
  buttonBackgroundActive: null,
  buttonBackgroundHover: null,
  buttonTextColor: null,
  menuBackground: null,
  resizeLineBackgroundColor: null,
  resizeLineBadgeBackgroundColor: null,
  listBoxPanelBackground: null,
  listBoxActiveBackgroundColor: null,
  listBoxHoverBackgroundColor: null,
  listBoxTextColor: null,
  listBoxActiveTextColor: null,
  scrollBarBackgroundColor: null,
  scrollBarHoverBackgroundColor: null,
  bottomBarBackgroundColor: null,
  bottomBarTextColor: null,
});
