name: '🐞 - Bug Report'
title: '🐞 - '
description: Report a bug in Codeimage
labels: [ 'bug', 'state: need triage' ]

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which @codeimage/* package(s) are the source of the bug?
      options:
        - codeimage
        - config
        - locale
        - highlight
        - ui
        - Don't known / other
      multiple: true
    validations:
      required: true

  - type: input
    id: reproduction-url
    attributes:
      label: Please provide a screenshot or a video to a minimal reproduction of the bug
      placeholder: "Enter an url or attach a file after submitting your issue"

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Please provide the exception or error you saw.
    validations:
      required: true

  - type: checkboxes
    id: browser-specific
    attributes:
      label: Which browsers have you used?
      description: You may select more than one.
      options:
        - label: Chrome
        - label: Firefox
        - label: Safari
        - label: Edge

  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which operating systems have you used?
      description: You may select more than one.
      options:
        - label: macOS
        - label: Windows
        - label: Linux
        - label: iOS
        - label: Android
