name: '🚀 - Feature Request'
title: '🚀 - '
description: Suggest a feature for Codeimage
labels: ['feature', 'state: need triage']

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which @codeimage/* package(s) are relevant/releated to the feature request?
      options:
        - codeimage
        - config
        - locale
        - highlight
        - ui
        - Don't known / other
      multiple: true

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Proposed solution.
        Alternatives considered.
    validations:
      required: true
