export * from './lib/core/createConfiguration';
export * from './lib/core/ConfigurationProvider';
export * from './lib/types/configuration';
export * from './lib/types/language-def';
export * from './lib/types/terminal-def';
export {SUPPORTED_LOCALES} from './lib/base/locales';
export {SUPPORTED_LANGUAGES} from './lib/base/languages';
export {SUPPORTED_THEMES} from './lib/base/themes';
export {EDITOR_BASE_SETUP} from './lib/base/editor-basic-setup';
